name: .NET Azure deployment

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore .\src\GuitarStringTensionCalculator.Core\
    - name: Build
      run: dotnet build .\src\GuitarStringTensionCalculator.Core\ --no-restore
    - name: Test
      run: dotnet test .\src\GuitarStringTensionCalculator.Core\ --no-build --verbosity normal
    - name: Publish
      run: dotnet publish .\src\GuitarStringTensionCalculator.Core\GuitarStringTensionCalculator.Core.csproj -c Release -o website
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.2
      with:
        name: website
        path: GuitarStringTensionCalculator/website/**
        if-no-files-found: error
