name: .NET Azure deployment

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  app-name: "GuitarStringTensionCalculator"
  rg-name: "Default-Web-WestEurope"

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore .\src\GuitarStringTensionCalculator.Core\
    - name: Build
      run: dotnet build .\src\GuitarStringTensionCalculator.Core\ --no-restore
    - name: Test
      run: dotnet test .\src\GuitarStringTensionCalculator.Core\ --no-build --verbosity normal
    - name: Publish
      run: dotnet publish .\src\GuitarStringTensionCalculator.Core\GuitarStringTensionCalculator.Core.csproj -c Release -o ${{ github.workspace }}/website
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.2
      with:
        name: website
        path: ${{ github.workspace }}/website/**
        if-no-files-found: error

  deploy_staging:
    needs: build
    runs-on: windows-latest

    environment:
      name: PROD
      url: ${{ steps.deploywebapp.outputs.webapp-url }}

    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.0.8
      with:
        name: website
        path: website

    - name: Login via Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy web app
      id: deploywebapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.app-name }}
        package: website

    - name: az cli logout
      run: az logout
