name: Check Pull Request

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore .\src\GuitarStringTensionCalculator.Core\
    - name: Build
      run: dotnet build .\src\GuitarStringTensionCalculator.Core\ --no-restore
    - name: Test
      run: dotnet test .\src\GuitarStringTensionCalculator.Core\ --no-build --verbosity normal
